rcar-gen5: util-linux: backport patch to fix build with glibc 2.43 on host
Backport an upstream util-linux patch from the whinlatter,v2 BSP patch
series to resolve a build failure when the host system uses glibc 2.43.

In glibc C23, the bsearch macro is required to be const-preserving,
which causes compilation errors in lsfd where a compound literal is
passed directly to bsearch without wrapping parentheses.

This error manifests as:
../lsfd-cmd/lsfd.c:1879:75: error: macro "bsearch" passed 6 arguments,
but takes just 5

The fix wraps the compound literal argument in parentheses, resolving
the macro expansion issue.

Upstream-Status: Backport [2.42
https://github.com/util-linux/util-linux/commit/711bda1441561bfd2eb6d45fe0bc789535c1f1a8]

The util-linux.inc file is updated to include the new patch file in
SRC_URI.

Signed-off-by: Dy Le <dy.le.yb@bp.renesas.com>
Signed-off-by: Hau Vo <hau.vo.ra@renesas.com>